const elementsDefaultConfigiOS = JSON.stringify(
  {
    playerId: '0127c158-74ac-4cc8-b5aa-733e21577cbd',
    customerId: '10eaf9b3-a987-4ac1-bf57-02ed042bcb3a',
    _appSettings: {
      appIsPaid: 0,
      appCategories: ['news'],
      appPageURL: 'https://example.com/web-equivalent-article-page',
      domainURL: 'https://example.com',
      appPrivacyPolicy: 1,
      storeURL: 'https://appstore.com/example',
      bundleID: '67196714',
    },
    settings: {
      outstreamSettings: null,
      outstreamAdAsContent: null,
      pauseAdWhenFinished: null,
      playbackMode: 0,
      defaultSoundMode: 1,
      nextVideoMode: 1,
      customization: {
        responsive: true,
        ratioWidth: 16,
        ratioHeight: 9,
        fixedWidth: null,
        fixedHeight: null,
        showMuteWatermark: null,
        showExpandButton: null,
        closedCaptionDefault: null,
        iconsColor: null,
        accentColor: null,
        tooltipTextColor: null,
        tooltipBackgroundColor: null,
        logoPosition: null,
        logoURL: null,
        orientation: null,
      },
      playlist: null,
      disableAdvertising: null,
      advertising: null,
      disableClickUrl: null,
      disableCTARendering: null,
      disableStoryProgressBarRendering: null,
      disableTitleRendering: null,
    },
    mediaId: null,
    mediaIdList: null,
    useMediaIdListAsPlaylist: false,
    playlistId: null,
    customParam1: null,
    customParam2: null,
    customParam3: null,
    customParam4: null,
    customParam5: null,
  },
  null,
  4,
);

const playspaceDefaultConfigiOS = JSON.stringify(
  {
    playerId: '56afa2b2-d843-4440-bf58-bafde848eda4',
    customerId: '10eaf9b3-a987-4ac1-bf57-02ed042bcb3a',
    storyId: null,
    _appSettings: {
      appIsPaid: 0,
      appCategories: ['news'],
      appPageURL: 'https://example.com/web-equivalent-article-page',
      domainURL: 'https://example.com',
      appPrivacyPolicy: 1,
      storeURL: 'https://appstore.com/example',
      bundleID: '67196714',
    },
    settings: {
      playbackMode: 0,
      defaultSoundMode: 1,
      nextVideoMode: 1,
      customization: {
        responsive: true,
        ratioWidth: 4,
        ratioHeight: 3,
        fixedWidth: null,
        fixedHeight: null,
        showMuteWatermark: null,
        showExpandButton: null,
        closedCaptionDefault: null,
        iconsColor: null,
        accentColor: null,
        tooltipTextColor: null,
        tooltipBackgroundColor: null,
        logoPosition: null,
        logoURL: null,
        orientation: 2,
      },
      playlist: null,
      disableAdvertising: null,
      advertising: null,
      disableClickUrl: null,
      disableCTARendering: null,
      disableStoryProgressBarRendering: null,
      disableTitleRendering: null,
    },
    customParam1: null,
    customParam2: null,
    customParam3: null,
    customParam4: null,
    customParam5: null,
  },
  null,
  4,
);

const elementsDefaultConfigAndroid = JSON.stringify(
  {
    playerId: '0127c158-74ac-4cc8-b5aa-733e21577cbd',
    customerId: '10eaf9b3-a987-4ac1-bf57-02ed042bcb3a',
    _appSettings: {
      appIsPaid: 0,
      appCategories: ['news'],
      appPageURL: 'https://example.com/web-equivalent-article-page',
      domainURL: 'https://example.com',
      appPrivacyPolicy: 1,
      storeURL: 'https://appstore.com/example',
    },
    settings: {
      outstreamSettings: null,
      outstreamAdAsContent: null,
      pauseAdWhenFinished: null,
      playbackMode: 0,
      defaultSoundMode: 1,
      nextVideoMode: 1,
      customization: {
        responsive: true,
        ratioWidth: 16,
        ratioHeight: 9,
        fixedWidth: null,
        fixedHeight: null,
        showMuteWatermark: null,
        showExpandButton: null,
        closedCaptionDefault: null,
        iconsColor: null,
        accentColor: null,
        tooltipTextColor: null,
        tooltipBackgroundColor: null,
        logoPosition: null,
        logoURL: null,
        orientation: null,
      },
      playlist: null,
      disableAdvertising: null,
      advertising: null,
      disableClickUrl: null,
      disableCTARendering: null,
      disableStoryProgressBarRendering: null,
      disableTitleRendering: null,
    },
    mediaId: null,
    mediaIdList: null,
    useMediaIdListAsPlaylist: null,
    playlistId: null,
    customParam1: null,
    customParam2: null,
    customParam3: null,
    customParam4: null,
    customParam5: null,
  },
  null,
  4,
);

const playspaceDefaultConfigAndroid = JSON.stringify(
  {
    playerId: '56afa2b2-d843-4440-bf58-bafde848eda4',
    customerId: '10eaf9b3-a987-4ac1-bf57-02ed042bcb3a',
    storyId: null,
    _appSettings: {
      appIsPaid: 0,
      appCategories: ['news'],
      appPageURL: 'https://example.com/web-equivalent-article-page',
      domainURL: 'https://example.com',
      appPrivacyPolicy: 1,
      storeURL: 'https://appstore.com/example',
    },
    settings: {
      playbackMode: 0,
      defaultSoundMode: 1,
      nextVideoMode: 1,
      customization: {
        responsive: true,
        ratioWidth: 4,
        ratioHeight: 3,
        fixedWidth: null,
        fixedHeight: null,
        showMuteWatermark: null,
        showExpandButton: null,
        closedCaptionDefault: null,
        iconsColor: null,
        accentColor: null,
        tooltipTextColor: null,
        tooltipBackgroundColor: null,
        logoPosition: null,
        logoURL: null,
        orientation: 2,
      },
      playlist: null,
      disableAdvertising: null,
      advertising: null,
      disableClickUrl: null,
      disableCTARendering: null,
      disableStoryProgressBarRendering: null,
      disableTitleRendering: null,
    },
    customParam1: null,
    customParam2: null,
    customParam3: null,
    customParam4: null,
    customParam5: null,
  },
  null,
  4,
);

export {
  elementsDefaultConfigiOS,
  playspaceDefaultConfigiOS,
  elementsDefaultConfigAndroid,
  playspaceDefaultConfigAndroid,
};